/** 
 *Action constants for Users.
 */


export const FETCH_CATEGORIES='FETCH_CATEGORIES';
export const RECIEVE_CATEGORIES='RECIEVE_CATEGORIES';

export const FETCH_CATEGORIES_BY_ID='FETCH_CATEGORIES_BY_ID';
export const RECIEVE_CATEGORIES_BY_ID='RECIEVE_CATEGORIES_BY_ID';

export const FETCH_EDIT_CATEGORY='FETCH_EDIT_CATEGORY';
export const RECIEVE_EDIT_CATEGORY='RECIEVE_EDIT_CATEGORY';

export const FETCH_CREATE_CATEGORY='FETCH_CREATE_CATEGORY';
export const RECIEVE_CREATE_CATEGORY='RECIEVE_CREATE_CATEGORY';

export const FETCH_UPDATED_BUDGET='FETCH_UPDATED_BUDGET';
export const RECIEVE_UPDATED_BUDGET='RECIEVE_UPDATED_BUDGET';

